"use client";

import { ChangeEvent, FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import type { SiteSettings } from "../lib/content-types";

export default function SettingsForm({ settings }: { settings: SiteSettings }) {
  const router = useRouter();
  const [form, setForm] = useState(settings);
  const [message, setMessage] = useState("");
  const [uploading, setUploading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch("/api/admin/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); setMessage(response.ok ? "Settings saved." : (await response.json()).error || "Unable to save settings."); if (response.ok) router.refresh(); }
  function update(field: keyof SiteSettings, value: string) { setForm((current) => ({ ...current, [field]: value })); }
  async function uploadProfile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (file.size > 10 * 1024 * 1024) { setMessage("Profile image must be 10 MB or smaller."); return; } setUploading(true); setMessage("Uploading profile image..."); try { const timestamp = Math.floor(Date.now() / 1000); const signatureResponse = await fetch("/api/admin/profile-upload-signature", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ timestamp }) }); if (!signatureResponse.ok) throw new Error("Unable to prepare upload."); const signature = await signatureResponse.json(); const body = new FormData(); body.append("file", file); body.append("api_key", signature.apiKey); body.append("timestamp", String(timestamp)); body.append("signature", signature.signature); body.append("folder", signature.folder); body.append("tags", signature.tags); const uploadResponse = await fetch(`https://api.cloudinary.com/v1_1/${signature.cloudName}/image/upload`, { method: "POST", body }); if (!uploadResponse.ok) throw new Error("Cloudinary rejected the image."); const uploaded = await uploadResponse.json() as { secure_url: string }; update("profilePictureUrl", uploaded.secure_url); setMessage("Profile image uploaded. Save profile to apply it."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to upload profile image."); } finally { setUploading(false); } }
  return <form onSubmit={submit} className="space-y-5"><Field label="Brand name" value={form.brandName} onChange={(value) => update("brandName", value)} /><Field label="Alias" value={form.alias} onChange={(value) => update("alias", value)} /><Field label="Photographer name" value={form.photographerName} onChange={(value) => update("photographerName", value)} /><Field label="Contact email" value={form.contactEmail} onChange={(value) => update("contactEmail", value)} type="email" /><label className="block text-xs uppercase tracking-widest text-neutral-400">Profile picture<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={uploadProfile} disabled={uploading} className="mt-2 block w-full text-sm text-neutral-300 file:mr-4 file:border-0 file:bg-white file:px-3 file:py-2 file:text-xs file:font-bold file:uppercase file:text-black" /><span className="mt-2 block normal-case tracking-normal text-neutral-500">{uploading ? "Uploading to Cloudinary..." : form.profilePictureUrl ? "Image uploaded and ready to save." : "Choose an image to upload."}</span></label><label className="block text-xs uppercase tracking-widest text-neutral-400">Bio<textarea value={form.bio} onChange={(event) => update("bio", event.target.value)} rows={6} className="mt-2 w-full border border-neutral-700 bg-black px-3 py-3 text-sm text-white" /></label>{message && <p className="text-sm text-neutral-300" role="status">{message}</p>}<button disabled={uploading} className="bg-white px-5 py-3 text-xs font-bold uppercase tracking-widest text-black disabled:opacity-50">Save profile</button></form>;
}

function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="block text-xs uppercase tracking-widest text-neutral-400">{label}<input type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full border border-neutral-700 bg-black px-3 py-3 text-sm text-white" /></label>; }