import { PhotoItem, SiteSettings, ServiceItem } from "./content-types";

export const FALLBACK_PHOTOS: PhotoItem[] = [
  {
    _id: "photo-1",
    title: "Marina Shadows",
    slug: "marina-shadows",
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCCgxSazzYzk8u8LO_8k4nIb9APNckoCyPnJWy1bmtA7YozmyOmnEiwsW5nBQCas4GRckxUOJMYGzdvh-H5Bmo2r_oS_XrcV5-4JX3d2jKqgh0H_IfTGkn_tq7qc1ixGLLOZQhg7G8qbu3yhdRQNQblCeUgawMHhj7h42GEBiLE_c62-fhBqhLNonHjeCdmAT101vTE24hcvKcuiUbvgUegfDKvZ2BXAYZJEv3reYK5EH0s13UurTmlTg",
    altText: "High contrast dramatic monochrome photograph of bustling Balogun market Lagos",
    caption: "Elongated morning shadows slanting across textured cobblestones, deep obsidian blacks, sharp highlights on moving pedestrian silhouettes.",
    featured: true,
    orientation: "portrait",
    category: "Street",
    cameraSpec: "24mm • ƒ/1.78 • 1/1250s • ISO 64",
    location: "Lagos Island, Nigeria",
    hardware: "iPhone 15 Pro Max",
    aspectRatio: 0.75,
  },
];

export const FALLBACK_SETTINGS: SiteSettings = {
  brandName: "POWER LENS",
  alias: "@gpoweredward",
  photographerName: "Edwards Godspower",
  bio: "Edwards Godspower is a documentary and fine-art mobile photographer obsessed with natural contrast, raw street rhythm, and unscripted human emotion.",
  contactEmail: "powerlensmedia@gmail.com",
  profilePictureUrl: FALLBACK_PHOTOS[0].imageUrl,
  heroPhotoUrl: FALLBACK_PHOTOS[0].imageUrl,
  socialLinks: [
    { platform: "Instagram", handle: "@gpoweredward", url: "https://www.instagram.com/gpoweredward?utm_source=qr&stkn=cmRxMmNhd3VrY2J4" },
    { platform: "Email Inquiries", handle: "powerlensmedia@gmail.com", url: "mailto:powerlensmedia@gmail.com" },
    {
      platform: "WhatsApp",
      handle: "+234 704 058 4105",
      url: "https://wa.me/2347040584105?text=Hi%20Godspower%2C%20I%20found%20your%20contact%20through%20your%20portfolio%20website%20and%20would%20love%20to%20discuss%20a%20photography%20project.",
    },
    { platform: "Facebook", handle: "Edwards Godspower", url: "https://www.facebook.com/profile.php?id=61571600835845" },
  ],
};

export const FALLBACK_SERVICES: ServiceItem[] = [
  {
    _id: "service-1",
    title: "Wedding Photography",
    slug: "wedding-photography",
    subtitle: "Your love story, preserved in every detail.",
    imageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=1200",
    category: "Wedding",
    sortOrder: 1,
    published: true,
  },
  {
    _id: "service-2",
    title: "Birthday Photoshoots",
    slug: "birthday-photoshoots",
    subtitle: "Portraits that belong in a magazine.",
    imageUrl: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&q=80&w=1200",
    category: "Portraits",
    sortOrder: 2,
    published: true,
  },
  {
    _id: "service-3",
    title: "Event Photography",
    slug: "event-photography",
    subtitle: "Every highlight, every expression captured.",
    imageUrl: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&q=80&w=1200",
    category: "Events",
    sortOrder: 3,
    published: true,
  },
  {
    _id: "service-4",
    title: "Convocation Shoots",
    slug: "convocation-shoots",
    subtitle: "Milestone moments deserve milestone photos.",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&q=80&w=1200",
    category: "Graduation",
    sortOrder: 4,
    published: true,
  },
  {
    _id: "service-5",
    title: "Food Photography",
    slug: "food-photography",
    subtitle: "Making dishes look as good as they taste.",
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=1200",
    category: "Commercial",
    sortOrder: 5,
    published: true,
  },
  {
    _id: "service-6",
    title: "Product Photography",
    slug: "product-photography",
    subtitle: "Clean, commercial grade product visuals.",
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=1200",
    category: "Commercial",
    sortOrder: 6,
    published: true,
  },
  {
    _id: "service-7",
    title: "Church Photography",
    slug: "church-photography",
    subtitle: "Worship moments preserved with reverence.",
    imageUrl: "https://images.unsplash.com/photo-1438232992991-995b7058bbb3?auto=format&fit=crop&q=80&w=1200",
    category: "Documentary",
    sortOrder: 7,
    published: true,
  },
  {
    _id: "service-8",
    title: "Nature Photography",
    slug: "nature-photography",
    subtitle: "The quiet beauty of the world around us.",
    imageUrl: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&q=80&w=1200",
    category: "Landscape",
    sortOrder: 8,
    published: true,
  },
];

